### ISSUE TITLE
there is no _caffe.so after make pycaffe

### ISSUE THREAD

**Issue by maolin23** [fyu/dilation#11]
hi, 

When I 

`make all`
`make test`
`make pycaffe`

there is no `_caffe.so` in `caffe-dilation/python/caffe`

and I try the `predict.py`
there is an error
`ImportError:  libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory`

I have already added the `build_master/python` into my PYTHONPATH

Does anyone know how to solve this problem?

Cheers,
Mao

**Comment by fyu** [comment]
is there _caffe.so in build_master/python?

**Comment by maolin23** [comment]
yes,
but when I copy `_caffe.so` to `caffe-dilation/python/caffe`
the errror is
`ImportError: libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory`

if i don't copy `_caffe.so` to `caffe-dilation/python/caffe`
the error is
`ImportErrorL no module name _caffe`

**Comment by maolin23** [comment]
solve!!
I do this
`export LD_LIBRARY_PATH={CAFFE-DILATION_DIR}/build_master/lib:${LD_LIBRARY_PATH}`

but i have another question about the image list
the images in the image list are original or they are padded to 900*900?
or i should do anything else to the images?

**Comment by fyu** [comment]
The input images for training and testing should be original.

**Comment by maolin23** [comment]
Sorry, I have another question
Could you tell me about the loss during training? 
When I use your code to training,  my loss is about 2、3 in the first 15 iteration.
After that, my loss increase to 50 ~ 80 and be stabled.
After 20K iterations,  it is still about 60~80.
I'm not sure the correctness of this situation....
Could you tell me this situation is normal or not?
What loss is correct?
(My training/testing input images are all original.)

Thanks a lot,
Mao
