### ISSUE TITLE
Upconvolution layer at the end of Dilated10 ?

### ISSUE THREAD

**Issue by paulineluc14** [fyu/dilation#18]
Hi there, 

First of all, great work ! :)

I noticed there is an upconvolution layer at the end of Dilated10, (see [here](https://github.com/fyu/dilation/blob/20b1b98c434ad3d8dc0f3a015f64d54c15afe5a5/models/dilation10_cityscapes_deploy.prototxt#L690-L707)).

Correct me if I'm wrong but I don't remember seeing this mentioned in the paper. Is this the model which led to the results presented in the paper ? Or perhaps it is a new one ? If so, could you kindly advise on whether you kept the same training procedure ?
Thanks ! Cheers,

Pauline

**Comment by fyu** [comment]
yes, I added an upconv in training cityscapes models because the high resolution of cityscapes data, which is the one presented in the paper. It follows the same training procedure described in the paper.

**Comment by paulineluc14** [comment]
Ok thanks !
