### ISSUE TITLE
apply_dilaton_conv_to_image_classification_such_as_imagenet

### ISSUE THREAD

**Issue by liu666666** [fyu/dilation#23]
hi，Thanks for your sharing!

The dilation is used for dense prediction,such as Semantic Segmentation. I have a naive idea, can we apply the dilation conv to the image classification task，such as imagenet? 

Do you know the work about this? Do you think the dilation will work for image classification?Is it worthy trying?

Thanks for your kindly help and nice work!

**Comment by fyu** [comment]
I know of someone who have been working on this idea.
