### ISSUE TITLE
"cudaSuccess (2 vs. 0)  out of memory" on GTX Titan 

### ISSUE THREAD

**Issue by rui2016** [fyu/dilation#5]
Hi Fisher,
since great results have been reported by using Dilated CNN, I'm thinking to use it as the segmentation engine for my research. After reading your paper, today I started to play around with your code. Strangely, I kept getting the out of memory errors when tried the predict script. After checking the closed issues, I changed the Caffe back to the commit 08c5df but got the same errors. 

I tried camvid, kitti and cityscapes. On camvid it worked, but not on the other two.  Since GTX has 12GB memory, "out of memory" seems very weird to me. Is there any hint from your side?

Does anybody else get the similar errors?

cheers
Rui

**Comment by rui2016** [comment]
By the way, I didn't use cudnn. Would that  be a problem?

**Comment by fyu** [comment]
Hi @rui2016, in the dilation network, majority of the convolutions have dilation 1, so they can benefit from cuDNN in terms of memory usages. The problem should be saved if cuDNN is enabled.

**Comment by saviogeorge** [comment]
May I know how this error was solved?
