### ISSUE TITLE
Get label images for evaluation

### ISSUE THREAD

**Issue by Timo-hab** [fyu/dilation#7]
Hi Fisher

Thanks for that great repository! Could you still tell me, how to convert the color images to label images, where each pixel has an ID that represents the ground truth label? Is there already a script? Thanks in advance!

Best
Timo

**Comment by fyu** [comment]
Which dataset are you talking about?

**Comment by Timo-hab** [comment]
I am talking about cityscapes dataset.

**Comment by fyu** [comment]
The CityScapes team provides scripts that can parse the label images and convert the labels: https://github.com/mcordts/cityscapesScripts

**Comment by brigits-ai** [comment]
What is the best way to convert the CamVid dataset output to single channel results (same issue, different dataset)?
